specVersion: 1.0.0
name: juno-dictionary
version: 1.0.0
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: A SubQuery project provide dictionary data & service for the Terra network
schema:
  file: ./schema.graphql
network:
  chainId: juno-1
  endpoint: https://rpc-juno.whispernode.com:443
  chainTypes: # This is a beta feature that allows support for any Cosmos chain by importing the correct protobuf messages
    cosmos.slashing.v1beta1:
      file: "./proto/cosmos/slashing/v1beta1/tx.proto"
      messages:
        - "MsgUnjail"
    cosmos.bank.v1beta1:
      file: "./proto/cosmos/bank/v1beta1/bank.proto"
      messages:
        - Metadata
    cosmos.gov.v1beta1:
      file: "./proto/cosmos/gov/v1beta1/tx.proto"
      messages:
        - "MsgVoteWeighted"
    cosmos.gov.v1beta1.gov: # Key is not used, it matches the one above and is inferred from the file
      file: "./proto/cosmos/gov/v1beta1/gov.proto"
      messages:
        - "WeightedVoteOption"
    cosmos.base.v1beta1: # needed by MsgInstantiateContract2
      file: "./proto/cosmos/cosmos.base.v1beta1.coin.proto"
      messages:
        - "Coin"
    cosmwasm.wasm.v1:
      file: "./proto/cosmwasm/wasm/v1/tx.proto"
      messages:
        - "MsgInstantiateContract2"
    juno.feeshare.v1:
      file: "./proto/juno/feeshare/v1/tx.proto"
      messages:
        - MsgRegisterFeeShare
        - MsgUpdateFeeShare
        - MsgCancelFeeShare
    osmosis.tokenfactory.v1beta1:
      file: "./proto/osmosis/tokenfactory/v1beta1/tx.proto"
      messages:
        - MsgCreateDenom
        - MsgMint
        - MsgBurn
        - MsgChangeAdmin
        - MsgSetDenomMetadata
        - MsgSetBeforeSendHook
        - MsgForceTransfer

dataSources:
  - kind: cosmos/Runtime
    # startBlock: 4136532
    startBlock: 7408909
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: cosmos/EventHandler
        - handler: handleMessage
          kind: cosmos/MessageHandler
